'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { KeyRound, Mail, MessageSquare } from 'lucide-react';
import { AuthHeading } from '@/components/auth/auth-shell';
import { Alert, AuthLoadingState } from '@/components/auth/feedback';
import { OtpChallengeForm } from '@/components/auth/otp-challenge-form';
import { useAuth } from '@/hooks/use-auth';
import { destinationFor } from '@/lib/auth/routes';
import type { MfaMethod, MfaType } from '@/lib/auth/types';

const METHOD_COPY: Record<MfaType, { title: string; detail: string; Icon: typeof MessageSquare }> = {
  sms: {
    title: 'SMS verification',
    detail: 'Receive a 6-digit verification code by SMS.',
    Icon: MessageSquare,
  },
  totp: {
    title: 'Authenticator app',
    detail: 'Enter the code generated by your authenticator app.',
    Icon: KeyRound,
  },
  email: {
    title: 'Email verification',
    detail: 'Receive a verification code at your registered email.',
    Icon: Mail,
  },
};

export default function MfaPage() {
  const router = useRouter();
  const { state, user, challenge, sendMfaChallenge, verifyMfa } = useAuth();
  const [chosen, setChosen] = useState<MfaMethod | null>(null);
  const [delivery, setDelivery] = useState<{ method: MfaType; error: string | null } | null>(null);

  // A single configured method needs no choosing.
  const method =
    chosen ?? (challenge && challenge.methods.length === 1 ? challenge.methods[0] : null);

  // The code is on its way until the send for this exact method has settled.
  const sending = method !== null && method.type !== 'totp' && delivery?.method !== method.type;
  const sendError = delivery?.method === method?.type ? (delivery?.error ?? null) : null;

  useEffect(() => {
    if (state === 'INITIALIZING') return;
    if (user) router.replace(destinationFor(user));
    else if (!challenge) router.replace('/login');
  }, [state, user, challenge, router]);

  useEffect(() => {
    if (!method || method.type === 'totp') return;
    const type = method.type;
    let cancelled = false;
    void sendMfaChallenge(type)
      .then(() => {
        if (!cancelled) setDelivery({ method: type, error: null });
      })
      .catch(() => {
        if (!cancelled) {
          setDelivery({
            method: type,
            error: 'We could not send your code. Choose another method or try again.',
          });
        }
      });
    return () => {
      cancelled = true;
    };
  }, [method, sendMfaChallenge]);

  if (state === 'INITIALIZING' || !challenge || user) return <AuthLoadingState />;

  if (!method) {
    return (
      <div className="space-y-7">
        <AuthHeading
          title="Confirm it is you"
          description="Choose how you would like to receive your verification code."
        />
        <ul className="space-y-3">
          {challenge.methods.map((item) => {
            const copy = METHOD_COPY[item.type];
            return (
              <li key={item.type}>
                <button
                  type="button"
                  onClick={() => setChosen(item)}
                  className="flex w-full items-start gap-3 rounded-xl border border-border bg-card p-4 text-left transition-colors hover:border-action/50 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-action/25"
                >
                  <copy.Icon className="mt-0.5 size-5 shrink-0 text-action" aria-hidden="true" />
                  <span>
                    <span className="block font-semibold text-foreground">{copy.title}</span>
                    <span className="mt-0.5 block text-sm text-text-muted">{copy.detail}</span>
                    {item.destination_masked && (
                      <span className="mt-1 block text-sm tracking-wide text-foreground">
                        {item.destination_masked}
                      </span>
                    )}
                  </span>
                </button>
              </li>
            );
          })}
        </ul>
        <p className="text-center text-sm text-text-muted">
          <Link href="/login" className="font-medium text-action underline-offset-4 hover:underline">
            Back to sign in
          </Link>
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-7">
      <AuthHeading
        title="Confirm it is you"
        description={METHOD_COPY[method.type].detail}
      />

      {sendError && <Alert tone="error">{sendError}</Alert>}
      {sending && <Alert tone="info">Sending your code…</Alert>}

      <OtpChallengeForm
        channel={method.type}
        destinationMasked={method.destination_masked}
        expiresAt={challenge.expires_at}
        resendAfter={30}
        submitLabel="Verify and continue"
        onVerify={async (code) => {
          const verified = await verifyMfa(method.type, code);
          router.replace(destinationFor(verified));
        }}
        onResend={
          method.type === 'totp'
            ? undefined
            : async () => {
                await sendMfaChallenge(method.type);
                return { expiresAt: challenge.expires_at, resendAfter: 30 };
              }
        }
        lockedFallback={
          <Alert tone="warning" title="Account locked for 15 minutes">
            <p>
              After five incorrect codes we lock the account for 15 minutes. Try again later, or{' '}
              <Link href="/forgot-password" className="font-medium text-action hover:underline">
                reset your password
              </Link>
              .
            </p>
          </Alert>
        }
      />

      {challenge.methods.length > 1 && (
        <button
          type="button"
          onClick={() => setChosen(null)}
          className="w-full rounded text-sm font-medium text-action underline-offset-4 hover:underline"
        >
          Use a different method
        </button>
      )}
    </div>
  );
}
